FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app

WORKDIR /app/model_engine

COPY requirements-base.txt requirements-base.txt
COPY requirements-api.txt requirements-api.txt

RUN python3 -m pip install --no-cache-dir -r requirements-api.txt

COPY . /app/model_engine

EXPOSE 8100

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8100"]
